### ISSUE TITLE
Compilation error when specifying a `sum` variant with 0 or more `ion` PIG types

### ISSUE THREAD

**Issue by alancai98** [partiql/partiql-ir-generator#109] opened 2022-01-21 02:59 UTC
When creating a `sum` variant with 0 or more `ion` PIG types (e.g. `(one_of_valid_values values::(* ion 0))` the following error is given:

```
Unresolved reference: asAnyElement
```

From the generated source code, the `asAnyElement` function is not defined for lists of `IonElement`s:

```Kotlin
/**
 * Creates an instance of [IonSchemaModel.ValidValuesSpec.OneOfValidValues].
 */
fun oneOfValidValues(
    values: kotlin.collections.List<com.amazon.ionelement.api.IonElement> = emptyList(),
    metas: MetaContainer = emptyMetaContainer()
): IonSchemaModel.ValidValuesSpec.OneOfValidValues =
    IonSchemaModel.ValidValuesSpec.OneOfValidValues(
        values = values.asAnyElement(),                  // <-- problematic loc
        metas = newMetaContainer() + metas
    )
```

A temporary workaround could be to define this extension function under the `org.partiql.pig.runtime` namespace:

```Kotlin
fun kotlin.collections.List<com.amazon.ionelement.api.IonElement>.asAnyElement() = map { it.asAnyElement() }
```

I think a long-term fix would be to add this extension function to PIG's runtime library.

**Comment by dlurton** [comment] 2022-02-09 17:56
Duplicate of #41.

**Closed** 2022-02-09 17:56 UTC
Labels: bug
